project:
  type: website
  output-dir: docs

website:
  title: "jingyiyang.github.io"
  navbar:
    left:
      - href: Final Project.qmd
        text: Final Project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



